name: RandomBox
version: '1.0-SNAPSHOT'
main: org.foodust.randomBox.RandomBox
api-version: '1.21'
libraries:
  - "net.kyori:adventure-api:4.17.0"
  - "net.kyori:adventure-platform-bukkit:4.3.2"
  - "net.kyori:adventure-text-minimessage:4.17.0"
commands:
  랜덤박스: